/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Main_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Main
 * Method:    deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_deinit
  (JNIEnv *, jclass);

/*
 * Class:     Main
 * Method:    sendTo
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_Main_sendTo
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     Main
 * Method:    recvFrame
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_Main_recvFrame
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
