/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_FNETLib */

#ifndef _Included_org_example_FNETLib
#define _Included_org_example_FNETLib
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_org_example_FNETLib_init
  (JNIEnv *, jclass, jstring);

JNIEXPORT void JNICALL Java_org_example_FNETLib_deinit
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_org_example_FNETLib_sendTo
  (JNIEnv *, jclass, jbyteArray);

JNIEXPORT jbyteArray JNICALL Java_org_example_FNETLib_recvFrame
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
